"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, ArrowRight, Pause, Play, RotateCcw, Menu, X, GitBranch as Github, BriefcaseBusiness as Linkedin, Mail, Download, Code2, Layers, Box } from "lucide-react";
import { profile, projects, capabilities, timeline, achievements } from "./content";
import Scene from "../components/Scene";
import ProjectCard from "../components/ProjectCard";
import ContactForm from "../components/ContactForm";
const defaults = { speed: 1, amplitude: 1, wireframe: false, color: "#2454ef" };
const navigation = [["work", "Work"], ["lab", "Playground"], ["about", "About"], ["experience", "Journey"]];
function SectionHeading({ number, label, title, text }) { return <div className="section-heading"><p className="eyebrow">{number} / {label}</p><div><h2>{title}</h2>{text && <p>{text}</p>}</div></div>; }
export default function Portfolio() {
  const [reduced, setReduced] = useState(true);
  const [paused, setPaused] = useState(false);
  const [menu, setMenu] = useState(false);
  const [skill, setSkill] = useState(1);
  const [lab, setLab] = useState(false);
  const [settings, setSettings] = useState(defaults);
  useEffect(() => {
    const query = matchMedia("(prefers-reduced-motion: reduce)");
    const update = () => setReduced(query.matches);
    update(); query.addEventListener("change", update);
    return () => query.removeEventListener("change", update);
  }, []);
  useEffect(() => {
    const close = event => { if (event.key === "Escape") setMenu(false); };
    window.addEventListener("keydown", close);
    return () => window.removeEventListener("keydown", close);
  }, []);
  const stopMotion = reduced || paused;
  const selected = capabilities[skill];
  const toggleMotion = () => { setReduced(false); setPaused(!stopMotion); };
  return <div className={stopMotion ? "portfolio motion-off" : "portfolio"}>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><a className="wordmark" href="#home" aria-label="Home"><span className="brand-mark">y.</span>{profile.wordmark}</a><nav className={menu ? "navigation is-open" : "navigation"} id="navigation" aria-label="Main navigation">{navigation.map(([id, label]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}<a className="nav-contact" href="#contact" onClick={() => setMenu(false)}>Let’s talk <ArrowUpRight size={15} /></a></nav><button className="menu-button" aria-label={menu ? "Close navigation" : "Open navigation"} aria-expanded={menu} aria-controls="navigation" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></header>
    <main id="main">
      <section className="hero" id="home" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> THE INTERACTIVE WORKSHOP</p><h1 id="hero-title">Interfaces<br />you can <span>feel.</span></h1><p className="hero-description">I’m {profile.name}, a web developer shaping thoughtful interfaces and unexpected digital experiences.</p><div className="hero-actions"><a className="button button-dark" href="#work">View my work <ArrowUpRight size={18} /></a><a className="text-link" href="#contact">Hire me <ArrowRight size={17} /></a></div><div className="hero-specialties"><span>DEVELOPMENT</span><i /><span>DESIGN</span><i /><span>3D & MOTION</span></div></div>
      <div className="hero-stage"><Scene paused={stopMotion} /><span className="scene-index">EXPERIMENT 001 / WAVE FIELD</span><div className="scene-caption"><span>Go on. Make a ripple.</span><button className="icon-button" aria-label={stopMotion ? "Enable animation" : "Pause animation"} onClick={toggleMotion}>{stopMotion ? <Play size={16} /> : <Pause size={16} />}</button></div><span className="orbit-label">BUILT TO BE EXPLORED ↗</span></div>
      <div className="hero-bottom"><span>Creative thinking. Considered engineering.</span><a href="#work">SCROLL TO EXPLORE <ArrowDown size={14} /></a><span>REACT / THREE.JS / JAVASCRIPT</span></div></section>
      <section id="work" className="section work-section"><SectionHeading number="01" label="SELECTED WORK" title={<>Made with purpose.<br /><span>Built with curiosity.</span></>} text="A closer look at the thinking, craft, and code behind the experience." /><div className="project-grid">{projects.map(project => <ProjectCard key={project.id} project={project} reduced={stopMotion} />)}</div></section>
      <section id="lab" className="lab-section"><div className="lab-copy"><p className="eyebrow">02 / THE PLAYGROUND</p><h2>Less watching.<br /><span>More playing.</span></h2><p>A small experiment in making the web feel a little more alive. Tune the surface, inspect the geometry, and make it your own.</p><div className="lab-facts"><span><Box size={18} /> Instanced geometry</span><span><Code2 size={18} /> Custom wave maths</span><span><Layers size={18} /> Real-time rendering</span></div><Link className="text-link" href="/projects/wave-field">How it’s made <ArrowUpRight size={16} /></Link></div><div className="lab-console"><div className="console-top"><span><i /> WAVE FIELD / LIVE LAB</span><span>001</span></div><div className="lab-viewport">{lab ? <Scene paused={stopMotion} settings={settings} /> : <div className="lab-start"><div className="lab-wire-grid" /><button className="button button-light" onClick={() => setLab(true)}><Play size={17} /> Launch experiment</button><p>Loads when you’re ready.</p></div>}</div><div className="lab-controls"><label>Amplitude <output>{settings.amplitude.toFixed(1)}</output><input aria-label="Wave amplitude" type="range" min="0" max="2" step="0.1" value={settings.amplitude} onChange={event => setSettings({ ...settings, amplitude: Number(event.target.value) })} /></label><label>Speed <output>{settings.speed.toFixed(1)}×</output><input aria-label="Wave speed" type="range" min="0.2" max="2" step="0.1" value={settings.speed} onChange={event => setSettings({ ...settings, speed: Number(event.target.value) })} /></label><label className="check-label"><input type="checkbox" checked={settings.wireframe} onChange={event => setSettings({ ...settings, wireframe: event.target.checked })} /> Wireframe</label><button className="icon-button" aria-label="Reset experiment" onClick={() => setSettings(defaults)}><RotateCcw size={17} /></button><button className="icon-button" aria-label={stopMotion ? "Play experiment" : "Pause experiment"} onClick={toggleMotion}>{stopMotion ? <Play size={17} /> : <Pause size={17} />}</button></div></div></section>
      <section id="about" className="section about-section"><div className="about-art" aria-hidden="true"><div className="about-cross">+</div><div className="about-orbit"><span>THINK</span><span>BUILD</span><span>REFINE</span><b>Always<br /><em>curious.</em></b></div><span className="about-art-caption">A WORK IN PROGRESS. BY DESIGN.</span></div><div className="about-copy"><p className="eyebrow">03 / THE PERSON BEHIND THE PIXELS</p><h2>A developer’s mind.<br /><span>A designer’s eye.</span></h2><p>{profile.about}</p><p>{profile.aboutMore}</p><div className="about-meta"><span>{profile.role}</span><span>{profile.location}</span></div>{profile.resume ? <a className="button button-outline" href={profile.resume} download>Download résumé <Download size={16} /></a> : <p className="placeholder-note">Résumé will be added here.</p>}</div></section>
      <section id="skills" className="section skills-section"><SectionHeading number="04" label="CAPABILITIES" title={<>Different tools.<br /><span>One connected experience.</span></>} /><div className="skills-layout"><div className="skill-tabs" role="tablist" aria-label="Developer capabilities">{capabilities.map((item, index) => <button key={item.id} id={`tab-${item.id}`} role="tab" aria-selected={skill === index} aria-controls="skill-panel" tabIndex={skill === index ? 0 : -1} onClick={() => setSkill(index)} onKeyDown={event => { let next; if (event.key === "ArrowRight" || event.key === "ArrowDown") next = (index + 1) % capabilities.length; if (event.key === "ArrowLeft" || event.key === "ArrowUp") next = (index + capabilities.length - 1) % capabilities.length; if (event.key === "Home") next = 0; if (event.key === "End") next = capabilities.length - 1; if (next !== undefined) { event.preventDefault(); setSkill(next); document.getElementById(`tab-${capabilities[next].id}`)?.focus(); } }}>{item.label}<ArrowUpRight size={20} /></button>)}</div><div className="skill-panel" id="skill-panel" role="tabpanel" tabIndex={0} aria-labelledby={`tab-${selected.id}`}><div className="skill-tokens">{selected.tools.map((tool, i) => <span key={tool} style={{ "--rotation": `${i % 2 ? 4 : -4}deg` }}>{tool}</span>)}</div><h3>{selected.title}</h3><p>{selected.text}</p><a className="text-link" href={`/projects/${selected.project}`}>{selected.evidence}<ArrowUpRight size={16} /></a></div></div></section>
      <section id="experience" className="section journey-section"><SectionHeading number="05" label="THE JOURNEY" title={<>Learning. Making.<br /><span>Moving forward.</span></>} text="The experience and education behind the work." /><div className="timeline">{timeline.map((item, i) => <article key={i}><div><p className="eyebrow">{item.type}</p><span>{item.period}</span></div><div><p className="eyebrow">{item.organization}</p><h3>{item.title}</h3><p>{item.description}</p>{item.placeholder && <span className="placeholder-label">Details to be added</span>}</div></article>)}</div><div className="open-source"><Github size={30} /><div><h3>Curiosity doesn’t clock out.</h3><p>{profile.github ? "Explore my repositories, experiments, and public contributions on GitHub." : "A space for open-source contributions, technical writing, and verified achievements."}</p>{achievements.map(item => <a key={item.url} href={item.url} target="_blank" rel="noreferrer">{item.title} ↗</a>)}</div>{profile.github ? <a className="text-link" href={profile.github} target="_blank" rel="noreferrer">Explore GitHub <ArrowUpRight size={17} /></a> : <span className="placeholder-label">GitHub profile to be added</span>}</div></section>
      <section id="contact" className="contact-section"><div><p className="eyebrow">06 / SOMETHING GOOD STARTS HERE</p><h2>Let’s make<br /><span>something matter.</span></h2><p>A new role, an ambitious project, or an interesting conversation. I’d love to hear what you have in mind.</p><div className="contact-links">{profile.email && <a href={`mailto:${profile.email}`}><Mail size={19} />{profile.email}</a>}{profile.github && <a href={profile.github} target="_blank" rel="noreferrer"><Github size={19} />GitHub ↗</a>}{profile.linkedin && <a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={19} />LinkedIn ↗</a>}{!profile.email && !profile.github && !profile.linkedin && <span>Direct contact and social links will be added here.</span>}</div></div><ContactForm /></section>
    </main><footer className="site-footer"><a className="wordmark" href="#home">{profile.wordmark}</a><span>Thoughtfully built with React & Three.js.</span><button onClick={toggleMotion} aria-pressed={stopMotion}>{stopMotion ? <Play size={13} /> : <Pause size={13} />}{stopMotion ? "Enable motion" : "Reduce motion"}</button><a href="#home">Back to top ↑</a></footer>
  </div>;
}
